databricks/docker-spark-iceberg

spark/Dockerfile
spark/spark-defaults.conf

I've tested this locally and it works.
Opening this as a draft, as we will need to release an updated image to dockerhub.
I would propose that we start by versioning the images according to `tabualrio/spark-iceberg:${spark_version}_${iceberg_versions`, so `tabulario/spark-iceberg:3.2.1_0.13.1`. We'd still need to account for image changes that occur without a version change.
In addition to versioning, I would still keep the most recent image on `latest` (and reserve that tag for mutable images).
In the case that we keep going with `latest`, we definitely need to provide clear instructions on how to remove the image and redownload the newest "latest". I think that `docker-compose kill && docker-compose rm && docker-compose pull` should cover it.
We might only need to tag the images for …

Upgrade Spark to 3.2.1 and use Iceberg 0.13.1

---

README.md

As we release new versions of the image (such as to upgrade Spark or the default Iceberg version), we continue to use the `latest` tag out of convenience.
This includes instructions in the README on force removing any existing `tabulario/docker-spark` images.
In a follow up, I'm also planning on reorganizing the image so that it benefits from more caching of layers that don't need to be pulled fresh every time.
cc @samredai

README - Add instructions for removing and pulling latest image

---

README.md
spark/Dockerfile

The notebook now supports kernels other than pyspark so this changes the command to start it to `notebook` (keeps `pyspark-notebook` for backwards-compatibility).

Add notebook command, equivalent to pyspark-notebook

---

docker-compose.yml
spark/Dockerfile
spark/entrypoint.sh
spark/requirements.txt

Hey @samredai I was giving Java part 2 blog a try and noticed that the container was kinda big and it took a while to download. I was able to reduce the size a bit, but is still a beefy container:
```
REPOSITORY                TAG             IMAGE ID       CREATED          SIZE
fokkospark                latest          297b172b3f5e   17 minutes ago   2.64GB
tabulario/spark-iceberg   latest          9701156a213b   2 days ago       3.18GB
```
83% of the original size, but with Spark it looks like we can't get it much smaller:
Tested by running:
- Iceberg - An Introduction to the Iceberg Java API.ipynb
- Iceberg - Integrated Audits Demo.ipynb

Reduce container size

---

README.md

Adds a link to the dockerhub repository to the README.
I wasn't quite sure where to place this, so I just added it to the bottom. Please feel free to suggest a better location / header.

Update README with link to dockerhub repository

---

docker-compose-w-minio.yml

This adds a variation of the docker-compose that uses a local minio container + S3FileIO for storage (instead of a local directory + HadoopFileIO). This is covered in [this](https://tabular.io/blog/minio/) blog post.

Add a docker-compose-w-minio.yml

---

spark/notebooks/Iceberg - An Introduction to the Iceberg Java API.ipynb

Bugfix in java api notebook. Missing an import and definition of the nyc namespace.

Add missing namespace definition in notebook example

---

dev/build-and-push-image.sh

Adds a simple shell script to push the image as a multi-platform image to dockerhub.
This script takes in the tag as an argument, and is set up to make it easy to change to support different repositories etc. It also checks if docker is installed and running, as well as validates the image tag is a valid image tag.
The tag defaults to latest if not provided.

Infra - Add script to push new image to Dockerhub

---

docker-compose.yml
spark/Dockerfile
spark/notebooks/Iceberg - Getting Started.ipynb
spark/notebooks/Iceberg - Table Maintenance Spark Procedures.ipynb

This PR does a few things:
- Add an example [notebook](https://github.com/tabular-io/docker-spark-iceberg/blob/685aa82e5993960fb8b02ab5886b2e5c526b09c4/spark/notebooks/Iceberg%20-%20Table%20Maintenance%20Spark%20Procedures.ipynb) for running table maintenance procedures
- Update the NYC data to use the new parquet files instead of CSV (also adds an entire year of data instead of just one month)
- Update the url for downloading Spark 3.2.1 since it's now been moved to the archives

Add table maintenance notebook and nyc taxi parquet files

---

spark/Dockerfile

This updates the main branch to use the new 0.14.0 release. I confirmed that the notebooks run without any issues using this new version. Once this is in I think we should cut a `3.2.1_0.14.0` branch and deploy that tag to dockerhub. Then we can start on updating the main branch to Spark 3.3.0 using the Iceberg-Spark runtime for Spark 3.3 and Iceberg 0.14.0.

Update Iceberg-Spark-runtime to use 3.2.1_0.14.0

---

spark/Dockerfile

This updates Spark to `3.3.0` and the Iceberg-Spark runtime to `3.3_2.12-0.14.0`. I confirmed that all of the notebooks run without any errors.

Updated Spark to 3.3.0 and the Iceberg-Spark-runtime to 3.3_2.12-0.14.0

---

spark/Dockerfile

It seems Spark 3.3.0 URL (https://dlcdn.apache.org/spark/spark-3.3.0/spark-3.3.0-bin-hadoop3.tgz) doesn't exist anymore. This PR updates it to 3.3.1

Update Spark CDN download link

---

docker-compose.yml

If you run `docker-compose up`, create some tables, and then run `docker-compose up` again, all the tables will be corrupted. This is because `mc` will run again, and will remove all the files in the bucket.

Keep the mc container alive

---

spark/entrypoint.sh

This is so that the spark shell can still be started while the thriftserver is running

Use separate derby folder for thriftserver

---

docker-compose.yml
spark/Dockerfile

This also requires the changes from https://github.com/tabular-io/iceberg-rest-image/pull/7

Update to Iceberg 1.2.0

---

.github/workflows/docker-image.yml

This also makes sure that `latest` tag is not pushed when an image is built from another branch.

Push latest tag when building image from main

---

spark/notebooks/Iceberg - Write-Audit-Publish (WAP) with Branches.ipynb

This is based on the existing `Iceberg - Integrated Audits Demo.ipynb`, and shows how to use a branch-based approach for WAP.

Add new notebook showing how to do WAP with branches

---

spark/Dockerfile

This PR adds the iceberg-azure bundle
Without this change, when using the AzureFileIO, queries fail with the below error
```
IllegalArgumentException: Cannot initialize FileIO implementation org.apache.iceberg.azure.adlsv2.ADLSFileIO: Cannot find constructor for interface org.apache.iceberg.io.FileIO
Missing org.apache.iceberg.azure.adlsv2.ADLSFileIO [java.lang.NoClassDefFoundError: com/azure/storage/file/datalake/models/DataLakeStorageException]
```
Confirmed, this error no longer happens after adding the runtime

Update dockerfile to add AzureFileIO runtime

---

docker-compose.yml

It appears that the command has changed. The log currently shows `mc: Please use 'mc anonymous'`.

fix(docker-compose): update mc policy command

---

docker-compose.yml

Causes:
```
WARN[0000] /Users/fokko.driesprong/Desktop/docker-spark-iceberg/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion
```

Remove `docker-compose.yml` version
